---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: clickhouse
    image: docker.io/centos:7
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    network: host

  - name: centos8
    image: docker.io/centos:8
    pre_build_image: true
    command: /usr/sbin/init
    privileged: true
    network: host

provisioner:
  name: ansible
verifier:
  name: ansible
