---
- name: Add Vector group
  ansible.builtin.group:
    name: vector
- name: Add Vector user
  ansible.builtin.user:
    name: vector
    group: vector
    groups: adm
- name: Get Vector archive
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/0.31.0/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/opt/"
  register: get_archive
- name: Unpack Vector binary
  ansible.builtin.unarchive:
    src: "/opt/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/opt/"
    remote_src: true
    owner: vector
  when: get_archive.changed
- name: Create data-directory
  ansible.builtin.file:
    path: "/opt/vector_data"
    state: directory
    owner: vector
    mode: "755"
- name: Upload SysV Vector config
  ansible.builtin.template:
    src: "templates/vectorv.toml"
    dest: "/opt/vector-x86_64-unknown-linux-musl/config/vector.toml"
    mode: "644"
  when: ansible_service_mgr == "sysvinit"
- name: Upload SystemD Vector config
  ansible.builtin.template:
    src: "templates/vectord.toml"
    dest: "/opt/vector-x86_64-unknown-linux-musl/config/vector.toml"
    mode: "644"
  when: ansible_service_mgr == "systemd"
- name: Upload SysV service script
  ansible.builtin.template:
    src: "./vector"
    dest: "/etc/init.d/"
    mode: "755"
  when: ansible_service_mgr == "sysvinit"
- name: Upload SystemD unit-file
  ansible.builtin.template:
    src: "./vector.service"
    dest: "/usr/lib/systemd/system/"
    mode: "644"
  when: ansible_service_mgr == "systemd"
- name: Start Vector
  ansible.builtin.service:
    name: vector
    state: started
  register: vector
