data_dir = "/opt/vector_data"

[sources.vector]
type = "file"
include = [ "/var/log/vector.log" ]

[sinks.clickhouse]
type = "clickhouse"
inputs = [ "vector" ]
database = "logs"
endpoint = "http://{{ clickhouse_host }}:8123"
table = "vector"
skip_unknown_fields = true